# need 4 gpus

project: coconut
save_path: outputs/prosqa/online_reversed
name: prosqa-coconut-online-reversed

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
reversed: True

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False

# --- dataset --- #
data_type: online # options: file or online
dataset: # used for online
  size:
    train: 17886
    valid: 300
    test: 500

  num_nodes: [5, 20]
  num_layers: [2, 5]
  connection_prob: 0.3
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json

# --- optimizer --- #
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 2
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01
