# need 4 gpus

project: coconut
save_path: YOUR_PATH_TO_SAVE_THE_MODEL
name: prosqa-coconut

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False
reversed: False

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: YOUR_PATH_TO_COCONUT_CHECKPOINT
seed: 0
resume: 40
bf16: False

# --- dataset --- #
data_type: file # options: file or synthetic
dataset: # used for online
  size:
    train: 17886
    valid: 300
    test: 500

  num_nodes: [5, 20]
  num_layers: [2, 5]
  connection_prob: 0.3
train_path: data/prontoqa_train.json
val_path: data/prontoqa_valid.json

# --- optimizer --- #
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01