defaults:
  - run: train
  - data: synthetic
  - method: coconut
  - model: gpt2_scratch_small
  - training: coconut
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false

